#!/usr/bin/env python

"""anova.py: A python version of ANOVA."""

__author__      = "Francisco Maria Calisto"
__maintainer__  = "Francisco Maria Calisto"
__email__       = "francisco.calisto@tecnico.ulisboa.pt"
__license__     = "ACADEMIC & COMMERCIAL"
__version__     = "1.0.0"
__status__      = "Production"
__copyright__   = "Copyright 2017, Instituto Superior Técnico (IST)"
__credits__     = [
                    "Carlos Santiago",
                    "Jacinto C. Nascimento",
                    "Pedro Miraldo",
                    "Nuno Nunes"
                  ]

import sys, os.path
sheetReader_dir = (os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
+ '/sheet-reader/src/')
sys.path.append(sheetReader_dir)

import pandas as pd
datafile = (os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
+ '/sheet-reader/temp/sheet.csv')

#data = pd.read_csv(datafile, error_bad_lines=False)

from main import sheetReader
from main import sheetReaderSum
from main import sheetReaderMean

constants_dir = (os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
+ '/statistical-analysis/constants/')
sys.path.append(constants_dir)
import sheets

MIN_VAL = sheets.MIN_VAL
MAX_VAL = sheets.MAX_VAL
N = MAX_VAL - MIN_VAL

GROUP_INTERN_1 = sheets.GROUP_INTERN_1
GROUP_INTERN_2 = sheets.GROUP_INTERN_2
GROUP_JUNIOR_1 = sheets.GROUP_JUNIOR_1
GROUP_JUNIOR_2 = sheets.GROUP_JUNIOR_2
GROUP_MIDDLE_1 = sheets.GROUP_MIDDLE_1
GROUP_MIDDLE_2 = sheets.GROUP_MIDDLE_2
GROUP_SENIOR_1 = sheets.GROUP_SENIOR_1
GROUP_SENIOR_2 = sheets.GROUP_SENIOR_2

GROUPS_LIST = [
                GROUP_INTERN_1,
                GROUP_INTERN_2,
                GROUP_JUNIOR_1,
                GROUP_JUNIOR_2,
                GROUP_MIDDLE_1,
                GROUP_MIDDLE_2,
                GROUP_SENIOR_1,
                GROUP_SENIOR_2
              ]

NASATLX_SINGLE_MENTAL_DEMAND = sheets.NASATLX_SINGLE_MENTAL_DEMAND
NASATLX_SINGLE_PHYSICAL_DEMAND = sheets.NASATLX_SINGLE_PHYSICAL_DEMAND
NASATLX_SINGLE_TEMPORAL_DEMAND = sheets.NASATLX_SINGLE_TEMPORAL_DEMAND
NASATLX_SINGLE_PERFORMANCE = sheets.NASATLX_SINGLE_PERFORMANCE
NASATLX_SINGLE_EFFORT = sheets.NASATLX_SINGLE_EFFORT
NASATLX_SINGLE_FRUSTRATION = sheets.NASATLX_SINGLE_FRUSTRATION

NASATLX_SINGLE_LIST = [
                        NASATLX_SINGLE_MENTAL_DEMAND,
                        NASATLX_SINGLE_PHYSICAL_DEMAND,
                        NASATLX_SINGLE_TEMPORAL_DEMAND,
                        NASATLX_SINGLE_PERFORMANCE,
                        NASATLX_SINGLE_EFFORT,
                        NASATLX_SINGLE_FRUSTRATION
                      ]

NASATLX_MULTI_MENTAL_DEMAND = sheets.NASATLX_MULTI_MENTAL_DEMAND
NASATLX_MULTI_PHYSICAL_DEMAND = sheets.NASATLX_MULTI_PHYSICAL_DEMAND
NASATLX_MULTI_TEMPORAL_DEMAND = sheets.NASATLX_MULTI_TEMPORAL_DEMAND
NASATLX_MULTI_PERFORMANCE = sheets.NASATLX_MULTI_PERFORMANCE
NASATLX_MULTI_EFFORT = sheets.NASATLX_MULTI_EFFORT
NASATLX_MULTI_FRUSTRATION = sheets.NASATLX_MULTI_FRUSTRATION

NASATLX_MULTI_LIST = [
                        NASATLX_MULTI_MENTAL_DEMAND,
                        NASATLX_MULTI_PHYSICAL_DEMAND,
                        NASATLX_MULTI_TEMPORAL_DEMAND,
                        NASATLX_MULTI_PERFORMANCE,
                        NASATLX_MULTI_EFFORT,
                        NASATLX_MULTI_FRUSTRATION
                     ]

# ============================================== #
#                 GROUP_INTERN_1                 #
# ============================================== #

NSMD_SUM_GI1 = sheetReaderSum(GROUP_INTERN_1, NASATLX_SINGLE_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NSPD_SUM_GI1 = sheetReaderSum(GROUP_INTERN_1, NASATLX_SINGLE_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NSTD_SUM_GI1 = sheetReaderSum(GROUP_INTERN_1, NASATLX_SINGLE_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NSP_SUM_GI1 = sheetReaderSum(GROUP_INTERN_1, NASATLX_SINGLE_PERFORMANCE, MIN_VAL, MAX_VAL)
NSE_SUM_GI1 = sheetReaderSum(GROUP_INTERN_1, NASATLX_SINGLE_EFFORT, MIN_VAL, MAX_VAL)
NSF_SUM_GI1 = sheetReaderSum(GROUP_INTERN_1, NASATLX_SINGLE_FRUSTRATION, MIN_VAL, MAX_VAL)

NMMD_SUM_GI1 = sheetReaderSum(GROUP_INTERN_1, NASATLX_MULTI_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NMPD_SUM_GI1 = sheetReaderSum(GROUP_INTERN_1, NASATLX_MULTI_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NMTD_SUM_GI1 = sheetReaderSum(GROUP_INTERN_1, NASATLX_MULTI_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NMP_SUM_GI1 = sheetReaderSum(GROUP_INTERN_1, NASATLX_MULTI_PERFORMANCE, MIN_VAL, MAX_VAL)
NME_SUM_GI1 = sheetReaderSum(GROUP_INTERN_1, NASATLX_MULTI_EFFORT, MIN_VAL, MAX_VAL)
NMF_SUM_GI1 = sheetReaderSum(GROUP_INTERN_1, NASATLX_MULTI_FRUSTRATION, MIN_VAL, MAX_VAL)

NSMD_MEAN_GI1 = sheetReaderMean(GROUP_INTERN_1, NASATLX_SINGLE_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NSPD_MEAN_GI1 = sheetReaderMean(GROUP_INTERN_1, NASATLX_SINGLE_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NSTD_MEAN_GI1 = sheetReaderMean(GROUP_INTERN_1, NASATLX_SINGLE_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NSP_MEAN_GI1 = sheetReaderMean(GROUP_INTERN_1, NASATLX_SINGLE_PERFORMANCE, MIN_VAL, MAX_VAL)
NSE_MEAN_GI1 = sheetReaderMean(GROUP_INTERN_1, NASATLX_SINGLE_EFFORT, MIN_VAL, MAX_VAL)
NSF_MEAN_GI1 = sheetReaderMean(GROUP_INTERN_1, NASATLX_SINGLE_FRUSTRATION, MIN_VAL, MAX_VAL)

NMMD_MEAN_GI1 = sheetReaderMean(GROUP_INTERN_1, NASATLX_MULTI_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NMPD_MEAN_GI1 = sheetReaderMean(GROUP_INTERN_1, NASATLX_MULTI_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NMTD_MEAN_GI1 = sheetReaderMean(GROUP_INTERN_1, NASATLX_MULTI_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NMP_MEAN_GI1 = sheetReaderMean(GROUP_INTERN_1, NASATLX_MULTI_PERFORMANCE, MIN_VAL, MAX_VAL)
NME_MEAN_GI1 = sheetReaderMean(GROUP_INTERN_1, NASATLX_MULTI_EFFORT, MIN_VAL, MAX_VAL)
NMF_MEAN_GI1 = sheetReaderMean(GROUP_INTERN_1, NASATLX_MULTI_FRUSTRATION, MIN_VAL, MAX_VAL)

# ============================================== #
# ============================================== #
# ============================================== #

# ============================================== #
#                 GROUP_INTERN_2                 #
# ============================================== #

NSMD_SUM_GI2 = sheetReaderSum(GROUP_INTERN_2, NASATLX_SINGLE_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NSPD_SUM_GI2 = sheetReaderSum(GROUP_INTERN_2, NASATLX_SINGLE_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NSTD_SUM_GI2 = sheetReaderSum(GROUP_INTERN_2, NASATLX_SINGLE_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NSP_SUM_GI2 = sheetReaderSum(GROUP_INTERN_2, NASATLX_SINGLE_PERFORMANCE, MIN_VAL, MAX_VAL)
NSE_SUM_GI2 = sheetReaderSum(GROUP_INTERN_2, NASATLX_SINGLE_EFFORT, MIN_VAL, MAX_VAL)
NSF_SUM_GI2 = sheetReaderSum(GROUP_INTERN_2, NASATLX_SINGLE_FRUSTRATION, MIN_VAL, MAX_VAL)

NMMD_SUM_GI2 = sheetReaderSum(GROUP_INTERN_2, NASATLX_MULTI_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NMPD_SUM_GI2 = sheetReaderSum(GROUP_INTERN_2, NASATLX_MULTI_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NMTD_SUM_GI2 = sheetReaderSum(GROUP_INTERN_2, NASATLX_MULTI_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NMP_SUM_GI2 = sheetReaderSum(GROUP_INTERN_2, NASATLX_MULTI_PERFORMANCE, MIN_VAL, MAX_VAL)
NME_SUM_GI2 = sheetReaderSum(GROUP_INTERN_2, NASATLX_MULTI_EFFORT, MIN_VAL, MAX_VAL)
NMF_SUM_GI2 = sheetReaderSum(GROUP_INTERN_2, NASATLX_MULTI_FRUSTRATION, MIN_VAL, MAX_VAL)

NSMD_MEAN_GI2 = sheetReaderMean(GROUP_INTERN_2, NASATLX_SINGLE_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NSPD_MEAN_GI2 = sheetReaderMean(GROUP_INTERN_2, NASATLX_SINGLE_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NSTD_MEAN_GI2 = sheetReaderMean(GROUP_INTERN_2, NASATLX_SINGLE_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NSP_MEAN_GI2 = sheetReaderMean(GROUP_INTERN_2, NASATLX_SINGLE_PERFORMANCE, MIN_VAL, MAX_VAL)
NSE_MEAN_GI2 = sheetReaderMean(GROUP_INTERN_2, NASATLX_SINGLE_EFFORT, MIN_VAL, MAX_VAL)
NSF_MEAN_GI2 = sheetReaderMean(GROUP_INTERN_2, NASATLX_SINGLE_FRUSTRATION, MIN_VAL, MAX_VAL)

NMMD_MEAN_GI2 = sheetReaderMean(GROUP_INTERN_2, NASATLX_MULTI_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NMPD_MEAN_GI2 = sheetReaderMean(GROUP_INTERN_2, NASATLX_MULTI_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NMTD_MEAN_GI2 = sheetReaderMean(GROUP_INTERN_2, NASATLX_MULTI_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NMP_MEAN_GI2 = sheetReaderMean(GROUP_INTERN_2, NASATLX_MULTI_PERFORMANCE, MIN_VAL, MAX_VAL)
NME_MEAN_GI2 = sheetReaderMean(GROUP_INTERN_2, NASATLX_MULTI_EFFORT, MIN_VAL, MAX_VAL)
NMF_MEAN_GI2 = sheetReaderMean(GROUP_INTERN_2, NASATLX_MULTI_FRUSTRATION, MIN_VAL, MAX_VAL)

# ============================================== #
# ============================================== #
# ============================================== #

# ============================================== #
#                 GROUP_JUNIOR_1                 #
# ============================================== #

NSMD_SUM_GJ1 = sheetReaderSum(GROUP_JUNIOR_1, NASATLX_SINGLE_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NSPD_SUM_GJ1 = sheetReaderSum(GROUP_JUNIOR_1, NASATLX_SINGLE_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NSTD_SUM_GJ1 = sheetReaderSum(GROUP_JUNIOR_1, NASATLX_SINGLE_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NSP_SUM_GJ1 = sheetReaderSum(GROUP_JUNIOR_1, NASATLX_SINGLE_PERFORMANCE, MIN_VAL, MAX_VAL)
NSE_SUM_GJ1 = sheetReaderSum(GROUP_JUNIOR_1, NASATLX_SINGLE_EFFORT, MIN_VAL, MAX_VAL)
NSF_SUM_GJ1 = sheetReaderSum(GROUP_JUNIOR_1, NASATLX_SINGLE_FRUSTRATION, MIN_VAL, MAX_VAL)

NMMD_SUM_GJ1 = sheetReaderSum(GROUP_JUNIOR_1, NASATLX_MULTI_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NMPD_SUM_GJ1 = sheetReaderSum(GROUP_JUNIOR_1, NASATLX_MULTI_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NMTD_SUM_GJ1 = sheetReaderSum(GROUP_JUNIOR_1, NASATLX_MULTI_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NMP_SUM_GJ1 = sheetReaderSum(GROUP_JUNIOR_1, NASATLX_MULTI_PERFORMANCE, MIN_VAL, MAX_VAL)
NME_SUM_GJ1 = sheetReaderSum(GROUP_JUNIOR_1, NASATLX_MULTI_EFFORT, MIN_VAL, MAX_VAL)
NMF_SUM_GJ1 = sheetReaderSum(GROUP_JUNIOR_1, NASATLX_MULTI_FRUSTRATION, MIN_VAL, MAX_VAL)

NSMD_MEAN_GJ1 = sheetReaderMean(GROUP_JUNIOR_1, NASATLX_SINGLE_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NSPD_MEAN_GJ1 = sheetReaderMean(GROUP_JUNIOR_1, NASATLX_SINGLE_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NSTD_MEAN_GJ1 = sheetReaderMean(GROUP_JUNIOR_1, NASATLX_SINGLE_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NSP_MEAN_GJ1 = sheetReaderMean(GROUP_JUNIOR_1, NASATLX_SINGLE_PERFORMANCE, MIN_VAL, MAX_VAL)
NSE_MEAN_GJ1 = sheetReaderMean(GROUP_JUNIOR_1, NASATLX_SINGLE_EFFORT, MIN_VAL, MAX_VAL)
NSF_MEAN_GJ1 = sheetReaderMean(GROUP_JUNIOR_1, NASATLX_SINGLE_FRUSTRATION, MIN_VAL, MAX_VAL)

NMMD_MEAN_GJ1 = sheetReaderMean(GROUP_JUNIOR_1, NASATLX_MULTI_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NMPD_MEAN_GJ1 = sheetReaderMean(GROUP_JUNIOR_1, NASATLX_MULTI_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NMTD_MEAN_GJ1 = sheetReaderMean(GROUP_JUNIOR_1, NASATLX_MULTI_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NMP_MEAN_GJ1 = sheetReaderMean(GROUP_JUNIOR_1, NASATLX_MULTI_PERFORMANCE, MIN_VAL, MAX_VAL)
NME_MEAN_GJ1 = sheetReaderMean(GROUP_JUNIOR_1, NASATLX_MULTI_EFFORT, MIN_VAL, MAX_VAL)
NMF_MEAN_GJ1 = sheetReaderMean(GROUP_JUNIOR_1, NASATLX_MULTI_FRUSTRATION, MIN_VAL, MAX_VAL)

# ============================================== #
# ============================================== #
# ============================================== #

# ============================================== #
#                 GROUP_JUNIOR_2                 #
# ============================================== #

NSMD_SUM_GJ2 = sheetReaderSum(GROUP_JUNIOR_2, NASATLX_SINGLE_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NSPD_SUM_GJ2 = sheetReaderSum(GROUP_JUNIOR_2, NASATLX_SINGLE_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NSTD_SUM_GJ2 = sheetReaderSum(GROUP_JUNIOR_2, NASATLX_SINGLE_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NSP_SUM_GJ2 = sheetReaderSum(GROUP_JUNIOR_2, NASATLX_SINGLE_PERFORMANCE, MIN_VAL, MAX_VAL)
NSE_SUM_GJ2 = sheetReaderSum(GROUP_JUNIOR_2, NASATLX_SINGLE_EFFORT, MIN_VAL, MAX_VAL)
NSF_SUM_GJ2 = sheetReaderSum(GROUP_JUNIOR_2, NASATLX_SINGLE_FRUSTRATION, MIN_VAL, MAX_VAL)

NMMD_SUM_GJ2 = sheetReaderSum(GROUP_JUNIOR_2, NASATLX_MULTI_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NMPD_SUM_GJ2 = sheetReaderSum(GROUP_JUNIOR_2, NASATLX_MULTI_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NMTD_SUM_GJ2 = sheetReaderSum(GROUP_JUNIOR_2, NASATLX_MULTI_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NMP_SUM_GJ2 = sheetReaderSum(GROUP_JUNIOR_2, NASATLX_MULTI_PERFORMANCE, MIN_VAL, MAX_VAL)
NME_SUM_GJ2 = sheetReaderSum(GROUP_JUNIOR_2, NASATLX_MULTI_EFFORT, MIN_VAL, MAX_VAL)
NMF_SUM_GJ2 = sheetReaderSum(GROUP_JUNIOR_2, NASATLX_MULTI_FRUSTRATION, MIN_VAL, MAX_VAL)

NSMD_MEAN_GJ2 = sheetReaderMean(GROUP_JUNIOR_2, NASATLX_SINGLE_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NSPD_MEAN_GJ2 = sheetReaderMean(GROUP_JUNIOR_2, NASATLX_SINGLE_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NSTD_MEAN_GJ2 = sheetReaderMean(GROUP_JUNIOR_2, NASATLX_SINGLE_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NSP_MEAN_GJ2 = sheetReaderMean(GROUP_JUNIOR_2, NASATLX_SINGLE_PERFORMANCE, MIN_VAL, MAX_VAL)
NSE_MEAN_GJ2 = sheetReaderMean(GROUP_JUNIOR_2, NASATLX_SINGLE_EFFORT, MIN_VAL, MAX_VAL)
NSF_MEAN_GJ2 = sheetReaderMean(GROUP_JUNIOR_2, NASATLX_SINGLE_FRUSTRATION, MIN_VAL, MAX_VAL)

NMMD_MEAN_GJ2 = sheetReaderMean(GROUP_JUNIOR_2, NASATLX_MULTI_MENTAL_DEMAND, MIN_VAL, MAX_VAL)
NMPD_MEAN_GJ2 = sheetReaderMean(GROUP_JUNIOR_2, NASATLX_MULTI_PHYSICAL_DEMAND, MIN_VAL, MAX_VAL)
NMTD_MEAN_GJ2 = sheetReaderMean(GROUP_JUNIOR_2, NASATLX_MULTI_TEMPORAL_DEMAND, MIN_VAL, MAX_VAL)
NMP_MEAN_GJ2 = sheetReaderMean(GROUP_JUNIOR_2, NASATLX_MULTI_PERFORMANCE, MIN_VAL, MAX_VAL)
NME_MEAN_GJ2 = sheetReaderMean(GROUP_JUNIOR_2, NASATLX_MULTI_EFFORT, MIN_VAL, MAX_VAL)
NMF_MEAN_GJ2 = sheetReaderMean(GROUP_JUNIOR_2, NASATLX_MULTI_FRUSTRATION, MIN_VAL, MAX_VAL)

# ============================================== #
# ============================================== #
# ============================================== #

# SSbetween_NSMD_GI1 = ((NSMD_SUM_GI1)**2 / N) - ((NSMD_SINGLE_MULTI_GI1)**2 / (N * 2))
# SSbetween_NSMD_GI2 = ((NSMD_SUM_GI2)**2 / N) - ((NSMD_SINGLE_MULTI_GI2)**2 / (N * 2))

# def ssBetweenNasa():
#   groupsList = GROUPS_LIST
#   nasaListSingle = NASATLX_SINGLE_LIST
#   nasaListMulti = NASATLX_MULTI_LIST
#   for i in range(len(groupsList)):
#     for j in range(len(nasaListSingle)):
#       for k in range(len(nasaListMulti)):
#         NS_SINGLE_SUM = sheetReaderSum(groupsList[i], nasaListSingle[j], MIN_VAL, MAX_VAL)
#         NS_MULTI_SUM = sheetReaderSum(groupsList[i], nasaListMulti[k], MIN_VAL, MAX_VAL)
#         NSMD_SINGLE_MULTI = NS_SINGLE_SUM + NS_MULTI_SUM
#         SSbetween = ((NS_SUM)**2 / N) - ((NSMD_SINGLE_MULTI_GI1)**2 / (N * 2))
#         return SSbetween

# ssBetweenNasa()
